### ISSUE TITLE
Index Out Of Bounds Error - atlas apply on crafted hcl document

### ISSUE THREAD

**Issue by TopherIsSwell** [ariga/atlas#1001]
I'm not sure what causes this or why, but I can consistently get an index OOB panic from a given (apparently valid) HCL doc. I don't know anything about HCL or atlas, but messing around with it I was able to produce this error which seems like it could be a security issue. Even if the HCL doc is invalid, I feel like this should be caught before attempting to index a null array. 

This hcl document was created from a sqlite3 database and was then applied to a mysql db to discover this bug.

## Expected Result
I would expect that any HCL document (especially a valid one) that can't be applied, would output an well formed error and exit with an error code, without attempting any pointer derefs that may be invalid.

## Observed Result
On sending a specially crafted HCL document to an empty MySQL database, I get a index out-of-bounds panic. While the document may not be valid (it appears to work on sqlite3 targets), indexing out of bounds seems like a bug that should be caught and this document should just be refused instead.

Output from `atlas schema apply`
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
ariga.io/atlas/sql/mysql.parseColumn({0x0?, 0xb?})
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/mysql/inspect.go:595 +0x45c
ariga.io/atlas/sql/mysql.ParseType({0x0, 0x0})
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/mysql/convert.go:109 +0x3e
ariga.io/atlas/schemahcl.(*TypeRegistry).Type(0xc0000a5e60, 0xc000314f60, {0x0, 0x0, 0x1?})
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/schemahcl/types.go:285 +0x135
ariga.io/atlas/sql/mysql.convertColumnType(0x8?)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/mysql/sqlspec.go:193 +0x33
ariga.io/atlas/sql/internal/specutil.Column(0xc0000b8d80, 0xc899a8)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/internal/specutil/convert.go:146 +0x215
ariga.io/atlas/sql/mysql.convertColumn(0xc0000b8d80, 0x415c45?)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/mysql/sqlspec.go:162 +0x3a
ariga.io/atlas/sql/internal/specutil.Table(0xc0000ba5a0, 0xc0000a3720, 0xc899b0, 0xc89958, 0xc899b8, 0xc899a0)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/internal/specutil/convert.go:95 +0x114
ariga.io/atlas/sql/mysql.convertTable(0xc0000ba5a0, 0x0?)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/mysql/sqlspec.go:95 +0x4f
ariga.io/atlas/sql/internal/specutil.Scan(0xc0003ce240, {0xc0000108a8, 0x1, 0xc0003ce3f0?}, {0xc000010840, 0x1, 0x1}, 0xc899c8)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/internal/specutil/convert.go:47 +0x370
ariga.io/atlas/sql/mysql.evalSpec(0xc0000104d0?, {0xbbdd60?, 0xc0003ce240?}, 0xc0003ce240?)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/sql/mysql/sqlspec.go:34 +0x110
ariga.io/atlas/schemahcl.EvalFunc.Eval(0xc00040fae8?, 0x415fa7?, {0xbbdd60?, 0xc0003ce240?}, 0xc00008bf01?)
	/home/topher/go/pkg/mod/ariga.io/atlas@v0.4.3-0.20220713104915-cda1480dd791/schemahcl/hcl.go:551 +0x33
ariga.io/atlas/cmd/atlas/internal/cmdapi.applyRun(0x110ab20, 0xc0000fdb90, {0x0?, 0x0}, {0xc000081ae0, 0x1, 0x1}, 0x0, 0x0, 0x0)
	/home/topher/go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.5.0/internal/cmdapi/schema.go:318 +0x28d
ariga.io/atlas/cmd/atlas/internal/cmdapi.CmdApplyRun(0x110ab20, {0xc28f93?, 0x4?, 0x4?})
	/home/topher/go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.5.0/internal/cmdapi/schema.go:288 +0x105
github.com/spf13/cobra.(*Command).execute(0x110ab20, {0xc000097740, 0x4, 0x4})
	/home/topher/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x1109ea0)
	/home/topher/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/topher/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/topher/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
main.main()
	/home/topher/go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.5.0/main.go:29 +0x114
```

## Steps to reproduce
My setup:
Using atlas v0.5.0 (compiled with go 1.18.4) on Fedora 36 (fully updated as of today).
Using Docker 20.10.17 and MySQL 8.0.27
From GNU Bash 5.1.16

```bash
# install atlas v0.5.0
go install ariga.io/atlas/cmd/atlas@v0.5.0

# Create a vanilla, empty, 8.0.27 MySQL server:
docker run --name atlas-db  -p 3306:3306  -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=main mysql:8.0.27

# create bad HCL Document
cat << EOF > atlas.hcl
table "annotations" {
  schema = schema.main
  column "term" {
    null = false
    type = sql("")
  }
}
schema "main" {
}
EOF

# Attempt to apply schema:
atlas schema apply -u "mysql://root:pass@localhost:3306/main" -f atlas.hcl
```

**Comment by rotemtam** [comment]
hey @TopherIsSwell,
Thanks for reaching out. I will review this and update back. 
Just as a side note - HCL documents are not dialect agnostic and so one it is not expected that you will be able to inspect something from SQLite and apply it on MySQL.

**Comment by TopherIsSwell** [comment]
confirmed this fixes the issue of the overflow. 
However, this causes a problem where valid SQLite3 schemas generate invalid HCL documents. See issue #1014 (which is probably a much lower priority issue).
