### ISSUE TITLE
Defect: Migrate Status fails after Dry Run

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#1037]
Failure scenario is as follows:

Setting up a toy model with an `atlas.hcl` and a `schema.hcl` as follows:

```hcl
env "local" {
    src = "schema.hcl"

    url = "postgres://user:pass@localhost:5432/db_name?sslmode=disable"
    dev = "postgres://user:pass@localhost:5432/db_name_shadow?sslmode=disable"

    schemas = ["public"]

    migration {
        dir = "file://migrations"

        format = "atlas"
    }
}
```

```hcl
schema "public" {}

table "users" {
    schema = schema.public

    column "id" {
        type = bigint

        null = false

        identity {
            generated = ALWAYS
        }
    }

    primary_key {
        columns = [column.id]
    }
}
```

And the migrations folder contains a single SQL file:

```sql
-- create "users" table
CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY ("id"));
```

Starting with a fresh database, after running only `CREATE DATABASE db_name`; and `CREATE DATABASE db_name_shadow`;.

Run `atlas migrate status --env local` and get the following output:

```
Migration Status: OK
  -- Current Version:	No version applied yet
  -- Next Version:	Already at latest version
  -- Available:		1
  -- Executed:		0
  -- Pending:		0
```

Run `atlas migrate apply --dry-run --env local` and get the following output:

```
Migrating to version 20220808074842.sql (1 migrations in total):

  -- migrating version 20220808074842.sql
    -> CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY ("id"));
  -- ok (153.518µs)

  -------------------------
  -- 185.923µs
  -- 1 migrations
  -- 1 sql statements
```

In the background, this creates an empty table in the atlas_schema_revisions schema:

```sql
# \dt+ atlas_schema_revisions.*;

                                                     List of relations
         Schema         |          Name          | Type  | Owner  | Persistence | Access method |    Size    | Description 
------------------------+------------------------+-------+--------+-------------+---------------+------------+-------------
 atlas_schema_revisions | atlas_schema_revisions | table | user   | permanent   | heap          | 8192 bytes | 
(1 row)

# select * from atlas_schema_revisions.atlas_schema_revisions;

 version | description | execution_state | executed_at | execution_time | hash | operator_version | meta 
---------+-------------+-----------------+-------------+----------------+------+------------------+------
(0 rows)
```

Now we run `atlas migrate status --env local` again and get the following output:

```
panic: runtime error: slice bounds out of range [:2] with capacity 1

goroutine 1 [running]:
ariga.io/atlas/cmd/atlas/internal/cmdapi.CmdMigrateStatusRun(0x11011e0, {0xc1bf93?, 0x6?, 0x6?})
	/home/runner/work/ariga/ariga/src/atlas/cmd/atlas/internal/cmdapi/migrate.go:474 +0x87b
github.com/spf13/cobra.(*Command).execute(0x11011e0, {0xc0001fdf80, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x10feee0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
main.main()
	/home/runner/work/ariga/ariga/src/atlas/cmd/atlas/main.go:29 +0x114
```

-----
Tool versions:

```
postgres (PostgreSQL) 14.4 (Ubuntu 14.4-1.pgdg22.04+1)
psql (PostgreSQL) 14.4 (Ubuntu 14.4-1.pgdg22.04+1)

atlas version v0.5.0
https://github.com/ariga/atlas/releases/tag/v0.5.0
```

**Comment by masseelch** [comment]
@jrmcpeek Thank you for taking the time to provide us with such a detailed issue description.

All of the above is fixed on the latest master :blush:
