### ISSUE TITLE
Nil pointer error when running atlas schema clean on Postgres

### ISSUE THREAD

**Issue by linuxluigi** [ariga/atlas#1269]
Hey I'm new to atlas and I really like it so far. You did a real go job here 🤩

When running `atlas schema clean --url postgres://USER:PASSWORD@HOST:5432/DB?sslmode=disable` I always into a nil pointer error:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe42bfc]

goroutine 1 [running]:
ariga.io/atlas/sql/schema.(*Realm).Schema(...)
        /go/pkg/mod/ariga.io/atlas@v0.8.1/sql/schema/schema.go:90
ariga.io/atlas/sql/internal/sqlx.(*Diff).RealmDiff(0x400038ca80?, 0x40004017a0, 0x0)
        /go/pkg/mod/ariga.io/atlas@v0.8.1/sql/internal/sqlx/diff.go:77 +0xac
ariga.io/atlas/cmd/atlas/internal/cmdapi.schemaCleanRun(0x4000153200, {0x0?, 0x0?, 0x0?}, {{0xffffdc9491f0?, 0x0?}, 0x0?})
        /go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.8.1/internal/cmdapi/schema.go:224 +0xdc
ariga.io/atlas/cmd/atlas/internal/cmdapi.schemaCleanCmd.func1(0x4000153200?, {0x400038b770?, 0x3?, 0x3?})
        /go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.8.1/internal/cmdapi/schema.go:198 +0x30
github.com/spf13/cobra.(*Command).execute(0x4000153200, {0x400038b710, 0x3, 0x3})
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0x1f96ec0)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.main()
        /go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.8.1/main.go:36 +0x164
exit status 2
```

I tried to run it against an empty Postgres database & with a filled database with `atlas migrate apply`.
The connection string works quite fine with other atlas commands. 

For me, it looks like, atlas could not find the Postgres schemas.

Tested on:
- MacBook M2
- Atlas versioned:
  - installed via brew:
    - v0.8.2-540fb6e-canary  
  - installed via go get:
    - v0.8.1
    - v0.8.0
    - v0.7.2
    - v0.6.5
 - Postgres via Docker:
   - 15.0
   - 14
   - 13

**Comment by a8m** [comment]
Thanks for reporting this, and sorry for the inconvenience, @linuxluigi.

I'll give it a look soon and will update this issue 🙏

**Comment by linuxluigi** [comment]
Wow, thank you a lot for solving it so fast ❤️
