### ISSUE TITLE
Automigrate fails when enums with GoType and SchemaType is specified

### ISSUE THREAD

**Issue by ChStark** [ariga/atlas#1571]
First of all I'm am new to atlas, I'm using it with ent wich I found to be a great tool.

I'm creating models and for some of them I need to use enums, a generified example of one of them is:

```go
package schema

import (
	"backends/datatypes"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/rs/xid"
	"time"
)

type CampaignType string

const (
	CampaignTypeCpm CampaignType = "CPM"
	CampaignTypeCpc              = "CPC"
	CampaignTypeCpa              = "CPA"
	CampaignTypeCpi              = "CPI"
	CampaignTypeRs               = "RS"
)

// Values provides list valid values for Enum.
func (CampaignType) Values() (kinds []string) {
	for _, s := range []CampaignType{CampaignTypeCpm, CampaignTypeCpc, CampaignTypeCpa, CampaignTypeCpi, CampaignTypeRs} {
		kinds = append(kinds, string(s))
	}
	return
}

// Campaign holds the schema definition for the Campaign entity.
type Campaign struct {
	ent.Schema
}

// Fields of the Campaign.
func (Campaign) Fields() []ent.Field {
	return []ent.Field{
		field.Other("id", xid.ID{}).Default(xid.New).SchemaType(map[string]string{dialect.Postgres: "public.xid"}).Immutable(),
		field.Other("owner_id", xid.ID{}).SchemaType(map[string]string{dialect.Postgres: "public.xid"}).Immutable(),
		field.Bool("allow_non_registered_users").Default(true),
		field.Bool("allow_registered_users").Default(true),
		field.Bool("is_active").Default(false),
		field.Bool("is_adult").Default(false),
		field.Bool("is_locked").Default(false),
		field.Bool("is_nsfw").Default(false),
		field.Enum("type").GoType(CampaignType("CPM")).SchemaType(map[string]string{dialect.Postgres: "campaign_type"}).Immutable(),
		//field.Enum("type").Values("CPM", "CPC", "CPA", "CPI", "RS").Immutable(),
		field.Float("ctr").Default(0).Comment("click through ratio"),
		field.Float("epa").Default(0).Comment("earning per acquisition"),
		field.Float("epc").Default(0).Comment("earnings per click"),
		field.Float("epm").Default(0).Comment("earning per mile impressions"),
		field.Int("cool_down").Default(0).Comment("in seconds"),
		field.Int64("unrealized_cost").Default(0).Comment("in USD cents"),
		field.Int64("budget").Default(0).Comment("in USD cents"),
		field.Int64("clicks").Default(0),
		field.Int64("conversions").Default(0),
		field.Int64("impressions").Default(0),
		field.Other("asn", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("browsers", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("cities", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("countries", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("device_types", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("device_vendors", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("languages", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("operating_systems", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("postal_codes", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("regions", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.Other("timezones", &datatypes.TextArray{}).SchemaType(map[string]string{dialect.Postgres: "citext[]"}).Optional().Nillable(),
		field.String("name"),
		field.Time("created").Default(time.Now).Immutable(),
		field.Time("last_computed_billing_cycle").Default(time.Now),
		field.Time("last_system_update").Default(time.Now),
		field.Time("last_user_update").Default(time.Now).UpdateDefault(time.Now),
	}
}

// Edges of the Campaign.
func (Campaign) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("owner", User.Type).Ref("campaigns").Required().Immutable().Unique().Field("owner_id"),
		edge.To("ad_units", AdUnit.Type),
	}
}

// Indexes of the Campaign.
func (Campaign) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id", "name").Unique(),
	}
}
```

After a successful migration using:
```go
client, err := ent.Open("postgres", os.Getenv("Db_Main_ConnectionString"))
if err != nil {
    log.Fatalf("failed opening connection to postgres: %v", err)
}
defer client.Close()
// Run the auto migration tool.
if err := client.Debug().Schema.Create(
    context.Background(),
    migrate.WithDropIndex(true),
    migrate.WithDropColumn(true),
); err != nil {
    log.Fatalf("failed creating schema resources: %v", err)
}
``` 

If I try to run the same migration again I receive:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x90d185]

goroutine 1 [running]:
ariga.io/atlas/sql/postgres.(*state).mayDropEnum(0xc0003900e0, 0xc0004bf2e0, 0x0, 0xc0002c9d40)
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:830 +0xa5
ariga.io/atlas/sql/postgres.(*state).alterTable.func1.1(0x18?, 0xc00007d000?)
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:416 +0x1138
ariga.io/atlas/sql/internal/sqlx.(*Builder).MapCommaErr(0xc0009a2050?, {0x1208e40?, 0xc0009a01f8?}, 0xc0004bf118)
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/internal/sqlx/sqlx.go:339 +0x152
ariga.io/atlas/sql/postgres.(*state).alterTable.func1(0xc0004bf2e0, {0xc0009a2050, 0x1, 0x1})
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:392 +0x1d8
ariga.io/atlas/sql/postgres.(*state).alterTable(0xc0003900e0, 0xc000051400, {0xc0009a2050?, 0x1, 0x1})
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:498 +0x112
ariga.io/atlas/sql/postgres.(*state).modifyTable(0xc0003900e0, {0x17b9158, 0xc00013e000}, 0xc000428960)
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:373 +0x1be
ariga.io/atlas/sql/postgres.(*state).plan(0xc0003900e0, {0x17b9158, 0xc00013e000}, {0xc00099fa40?, 0xc000159d40?, 0xc0004bf6e8?})
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:91 +0x231
ariga.io/atlas/sql/postgres.(*planApply).PlanChanges(0xc0001421e0, {0x17b9158, 0xc00013e000}, {0x13ea0e1, 0x7}, {0xc00099fa40, 0x3, 0x3}, {0x0, 0x0, ...})
        /home/jorge/go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:42 +0x1d2
entgo.io/ent/dialect/sql/schema.(*Atlas).diff(0xc0001d8c00, {0x17b9158, 0xc00013e000}, {0x13ea0e1, 0x7}, 0x2?, 0x415b4d?, {0x0, 0x0, 0x0}, ...)
        /home/jorge/go/pkg/mod/entgo.io/ent@v0.11.10/dialect/sql/schema/atlas.go:813 +0x288
entgo.io/ent/dialect/sql/schema.(*Atlas).planInspect(0xc0001d8c00, {0x17b9158, 0xc00013e000}, {0x7f115007b2a0, 0xc000306bc0}, {0x13ea0e1, 0x7}, {0x1f64560, 0x13, 0x13})
        /home/jorge/go/pkg/mod/entgo.io/ent@v0.11.10/dialect/sql/schema/atlas.go:725 +0x449
entgo.io/ent/dialect/sql/schema.(*Atlas).create.func3(0xc0001d8c00, {0x17b9158, 0xc00013e000}, {0x17b9318?, 0xc000306bc0}, {0x1f64560, 0x13, 0x13})
        /home/jorge/go/pkg/mod/entgo.io/ent@v0.11.10/dialect/sql/schema/atlas.go:667 +0xc7
entgo.io/ent/dialect/sql/schema.(*Atlas).create(0xc0001d8c00, {0x17b9158, 0xc00013e000}, {0x1f64560?, 0x1fea560?, 0xc00007f890?})
        /home/jorge/go/pkg/mod/entgo.io/ent@v0.11.10/dialect/sql/schema/atlas.go:687 +0x511
entgo.io/ent/dialect/sql/schema.CreateFunc.Create(0xc00004cf90?, {0x17b9158?, 0xc00013e000?}, {0x1f64560?, 0xc0004bfc98?, 0x9e88af?})
        /home/jorge/go/pkg/mod/entgo.io/ent@v0.11.10/dialect/sql/schema/migrate.go:127 +0x3b
entgo.io/ent/dialect/sql/schema.(*Atlas).Create(0xc0001d8c00, {0x17b9158, 0xc00013e000}, {0x1f64560, 0x13, 0x13})
        /home/jorge/go/pkg/mod/entgo.io/ent@v0.11.10/dialect/sql/schema/atlas.go:118 +0x153
backends/ent/migrate.Create({0x17b9158, 0xc00013e000}, 0xc00004e019?, {0x1f64560, 0x13, 0x13}, {0x0?, 0x0?, 0x0?})
        /home/jorge/Projects/memesya/backends/ent/migrate/migrate.go:54 +0xb6
backends/ent/migrate.(*Schema).Create(...)
        /home/jorge/Projects/memesya/backends/ent/migrate/migrate.go:45
backends/cmds.Automigrate(0xc0002b8f00?, {0x13e6832?, 0x0?, 0x0?})
        /home/jorge/Projects/memesya/backends/cmds/automigrate.go:19 +0x10b
github.com/spf13/cobra.(*Command).execute(0xc0002b8f00, {0x219c550, 0x0, 0x0})
        /home/jorge/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f72e20)
        /home/jorge/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jorge/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
backends/cmds.Execute()
        /home/jorge/Projects/memesya/backends/cmds/root.go:30 +0x25
main.main()
        /home/jorge/Projects/memesya/backends/main.go:8 +0x17
```

I tried to analyze the method `mayDropEnum` in `go/pkg/mod/ariga.io/atlas@v0.10.0/sql/postgres/migrate.go:830`, but it seems that the var `ns` is coming as `nil` and there is no validation for that (even if that is being used to iterate a schema slice after that, is going to fail since it is trying to access properties from the variable), I could easily introduce a nil validation, but I don't know if that is a symptom of something bad at another level since I don't know the code

**Comment by a8m** [comment]
Thanks for opening this issue, @ChStark. Unfortunately, Ent does not support custom `SchemaType` for enums at this stage, because there’s no easy way to alter their values in PostgreSQL. 

If you still want to use database enums, you can use versioned migration, create the PostgreSQL `enum` type there, and then use it in the Ent schema.
