### ISSUE TITLE
panic: interface conversion: *sqltool.GolangMigrateDir is not interface { Path() string }: missing method Path

### ISSUE THREAD

**Issue by piotratlz** [ariga/atlas#1659]
Atlas version:
```sh
atlas version
atlas version v0.11.1-7309baf-canary
https://github.com/ariga/atlas/releases/latest
```

I'm trying to run the following command:
```bash
atlas migrate lint --dir file://./migrations --dev-url='postgres://postgres:postgres@localhost:5555/test?sslmode=disable' --dir-format golang-migrate --git-base origin/main
 ```
 The error I get is:
 ```sh
 panic: interface conversion: *sqltool.GolangMigrateDir is not interface { Path() string }: missing method Path
 ```
 Full stack trace:
 ```sh
 panic: interface conversion: *sqltool.GolangMigrateDir is not interface { Path() string }: missing method Path

goroutine 1 [running]:
ariga.io/atlas/cmd/atlas/internal/cmdapi.migrateLintRun(0xc000378600, {0x0?, 0x0?, 0x0?}, {{0xc00010e120, 0x41}, {0x307ab6962, 0xe}, {0x307ab690f, 0x45}, ...})
        /Users/runner/work/ariga/ariga/src/atlas/cmd/atlas/internal/cmdapi/migrate.go:864 +0x3a5
ariga.io/atlas/cmd/atlas/internal/cmdapi.migrateLintCmd.func2(0xc000378600?, {0xc0001d87e0?, 0x7?, 0x7?})
        /Users/runner/work/ariga/ariga/src/atlas/cmd/atlas/internal/cmdapi/migrate.go:823 +0x5c
github.com/spf13/cobra.(*Command).execute(0xc000378600, {0xc0001d8690, 0x7, 0x7})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x10327e5e0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(0x101d38020?, {0x101d3a198?, 0xc00047be80?})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985 +0x4a
main.main()
        /Users/runner/work/ariga/ariga/src/atlas/cmd/atlas/main.go:36 +0x10c
 ```
 
Panicking line: https://github.com/ariga/atlas/blob/master/cmd/atlas/internal/cmdapi/migrate.go#L864

It looks that  `sqltool.GolangMigrateDir` doesn't have method `Path()`:  https://github.com/ariga/atlas/blob/master/cmd/atlas/internal/cmdapi/migrate.go#LL1517C10-L1517C10

https://github.com/ariga/atlas/blob/8705b0e0ed50fefd7c36123c088506340f5be37e/sql/sqltool/tool.go#L76

**Comment by piotratlz** [comment]
Hi @giautm , works fine now. Thank you!
