### ISSUE TITLE
Incorrect architecture of atlas-ls in linux-aarch64

### ISSUE THREAD

**Issue by emdfonseca** [ariga/atlas#2498]
Hi!

I'm running an Ubuntu aarch64 devcontainer in vscode (host is an Apple M1).

```shell
$ uname -a
Linux c87d8c7b8fe0 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 22:39:36 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

When installing the Atlas HCL extension inside the devcontainer I get a vscode notification error and the output panel displays the following:

```less
[Error - 10:44:37 PM] Client AtlasHCL Language Server: connection to server is erroring. Shutting down server.
[Error - 10:44:37 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
    at b.shutdown (/home/golang/.vscode-server/extensions/ariga.atlas-hcl-0.4.3/dist/extension.js:1:90251)
    at b.stop (/home/golang/.vscode-server/extensions/ariga.atlas-hcl-0.4.3/dist/extension.js:1:89832)
    at b.stop (/home/golang/.vscode-server/extensions/ariga.atlas-hcl-0.4.3/dist/extension.js:1:251883)
    at b.handleConnectionError (/home/golang/.vscode-server/extensions/ariga.atlas-hcl-0.4.3/dist/extension.js:1:96339)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 10:44:37 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:44:37 PM] AtlasHCL Language Server client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 10:44:37 PM] Connection to server got closed. Server will restart.
true
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[Error - 10:44:37 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:44:37 PM] Connection to server got closed. Server will restart.
```

This hinted me that the architecture could be wrong which I confirmed:

```shell
$ file atlas-ls
atlas-ls: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e8e9fc449943f935d469333b1101f224a4c0164f, for GNU/Linux 2.6.32, stripped
```

While trying to understand the issue I modified the extension.js file to download the file `https://release.ariga.io/atlas-ls/atlas-ls-linux-arm64-latest`.

After this I no longer get a vscode notification error but the language server is still not launching correctly and I get the following in the ouput panel:

```less
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/snapshot/language-tools/packages/language-server/dist/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0
[Error - 10:50:41 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:50:41 PM] Connection to server got closed. Server will restart.
```

The Atlas CLI is working perfectly in linux aarch64.

It would be nice for the Atlas HCL extension to support Linux-aarch64 architecture, and the extension should be updated to correctly identify aarch64 as arm64 instead of x86-64.

Thank you for your attention to this matter.

**Comment by datdao** [comment]
Hi @emdfonseca, thank you for providing a detailed explanation of the issue. I will investigate it and reply to you soon

**Comment by datdao** [comment]
Hi @emdfonseca, we released a new version of the VSCode Extension yesterday (v0.4.4) with the fix for the issue. Please upgrade. If you encounter any errors after upgrading, let me know

**Comment by emdfonseca** [comment]
Hi @datdao , thanks for the update!

While the arch is now correctly detected and the download is successful the language server does not start. 

This is what I see in the Atlas HCL extension output panel:

```shell
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/snapshot/language-tools/packages/language-server/dist/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0
[Error - 9:34:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:34:00 PM] Connection to server got closed. Server will restart.
true
[Error - 9:34:00 PM] AtlasHCL Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:949
  throw err;
  ^
```

**Comment by giautm** [comment]
Hello @emdfonseca, I've found the root-cause. It was because we forgot to add `QEMU` for linux-arrch64. Please uninstall the extension and install again. The new binary for linux-arrch64 should work well.

Please let me known if the issue was fixed or not.

**Comment by emdfonseca** [comment]
Thank you! Everything working fine now.
