### ISSUE TITLE
atlas-provider-django install fails due to mysqlclient: Cannot find valid pkg-config name. 

### ISSUE THREAD

**Issue by nullbio** [ariga/atlas#2838]
I'm using Ubuntu 24.04 and python 3.12.3 on WSL2, without mysql installed on the system.

Anyway, when installing atlas-provider-django, it fails with the following pkg-config error below.

I've installed atlas via brew (`brew install ariga/tap/atlas`). I've also installed the following dependencies in an attempt to fix the below, which is commonly quoted as being the solution online to getting mysqlclient to install using pip:

`sudo apt install libmysqlclient-dev default-libmysqlclient-dev python3-dev pkg-config`

This made no difference.

I did however get it to work by doing:

`brew install pkg-config mysql-client`

The caveat is that I had to do add this env var afterward for pip install to work:

```
export PKG_CONFIG_PATH="$(brew --prefix)/opt/mysql-client/lib/pkgconfig"
```

This is clunky and people shouldn't need to manually install mysql-client like this for them to be able to install `atlas-provider-django`. 

However I noticed if I `pip install mysql-connector`  before I install mysqlclient, it works without error and without the above export.

I believe the root cause of this is because I do not have mysql installed in my system already. If I `brew install mysql`, pip will install mysqlclient without any errors. However, this shouldn't be a requirement to install `atlas-provider-django`, because the user may be using it with a different database.

**PROPOSAL:** I propose that `mysql-connector` be added as a dependency to `atlas-provider-django` to resolve this issue for other people in the future who are not using mysql with atlas-provider-django, so they aren't forced to install mysql server or do manual env var adjustments. 

```
pip install mysqlclient
Collecting mysqlclient
  Using cached mysqlclient-2.2.4.tar.gz (90 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Trying pkg-config --exists libmariadb
      Command 'pkg-config --exists libmariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "~/projects/junkyard/piptest/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "~/projects/junkyard/piptest/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~/projects/junkyard/piptest/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kekdbj__/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kekdbj__/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-kekdbj__/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 155, in <module>
        File "<string>", line 49, in get_config_posix
        File "<string>", line 28, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
```

**Comment by rotemtam** [comment]
Django and Atlas are used with other databases. Would a Postgres user would be happy to see MySQL deps forced upon them?

**Comment by ronenlu** [comment]
@nullbio Thank you for raising the issue!
We released a new version of `atlas-provider-django` that don't have specific database dependency.

You can try it by running: `pip install atlas-provider-django`

**Comment by ronenlu** [comment]
@nullbio thank you for raising the issue!
We fixed the issue, and released a new [version](https://pypi.org/project/atlas-provider-django/), you can install it by running:
```
pip install atlas-provider-django
```
